# Generated by Django 5.2.14 on 2026-05-27 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=200)),
                ('reminder_type', models.CharField(choices=[('MEDICATION', 'Medication'), ('APPOINTMENT', 'Appointment'), ('FOLLOWUP', 'Follow-up'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('reminder_message', models.TextField()),
                ('reminder_date', models.DateField()),
                ('reminder_time', models.TimeField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'reminder_date'], name='reminders_r_status_0f30ec_idx')],
            },
        ),
    ]
