# Generated by Django 5.2.14 on 2026-07-18 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_clinic_appointment_additional_notes_and_more'),
        ('reminders', '0004_reminder_completed_at_alter_reminder_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='appointments.appointment'),
        ),
    ]
