# Generated by Django 5.2.14 on 2026-07-11 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('slug', models.SlugField(max_length=180, unique=True)),
                ('category', models.CharField(choices=[('MALARIA', 'Malaria'), ('DIABETES', 'Diabetes'), ('HYPERTENSION', 'Hypertension'), ('PREGNANCY', 'Pregnancy'), ('NUTRITION', 'Nutrition'), ('MENTAL_HEALTH', 'Mental Health'), ('CHILD_HEALTH', 'Child Health'), ('VACCINATION', 'Vaccination')], max_length=20)),
                ('summary', models.CharField(help_text='One or two sentences shown in listings.', max_length=300)),
                ('content', models.TextField(help_text='Full article body. Informational only — no diagnosis or prescriptions.')),
                ('image', models.ImageField(blank=True, null=True, upload_to='health_library/')),
                ('is_published', models.BooleanField(default=True, help_text='Only published articles appear in the library.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['title'],
                'indexes': [models.Index(fields=['category', 'is_published'], name='health_libr_categor_788006_idx')],
            },
        ),
    ]
