# Generated by Django 5.2.14 on 2026-07-11 11:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('APPOINTMENT_CONFIRMED', 'Appointment confirmed'), ('REMINDER_CREATED', 'New reminder created'), ('REMINDER_COMPLETED', 'Reminder completed'), ('PROFILE_UPDATED', 'Profile updated')], max_length=32)),
                ('title', models.CharField(max_length=120)),
                ('message', models.CharField(blank=True, max_length=300)),
                ('url', models.CharField(blank=True, help_text='Optional link opened when the notification is clicked.', max_length=300)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read', '-created_at'], name='notificatio_user_id_f2ad08_idx')],
            },
        ),
    ]
