# Generated by Django 5.2.14 on 2026-07-18 18:17

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_appointment_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('opens_weekday', models.TimeField(default=datetime.time(8, 0))),
                ('closes_weekday', models.TimeField(default=datetime.time(17, 0))),
                ('opens_saturday', models.TimeField(default=datetime.time(8, 0))),
                ('closes_saturday', models.TimeField(default=datetime.time(13, 0))),
                ('open_sunday', models.BooleanField(default=False)),
                ('slot_capacity', models.PositiveSmallIntegerField(default=2, help_text='Maximum appointments allowed in a single 30-minute slot.')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='appointment',
            name='additional_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='appointment_type',
            field=models.CharField(choices=[('GENERAL', 'General Consultation'), ('FOLLOWUP', 'Follow-up'), ('SPECIALIST', 'Specialist'), ('VACCINATION', 'Vaccination'), ('LAB', 'Laboratory Test'), ('TELECONSULT', 'Teleconsultation')], default='GENERAL', max_length=20),
        ),
        migrations.AddField(
            model_name='appointment',
            name='source',
            field=models.CharField(choices=[('WEB', 'Web'), ('CHATBOT', 'Chatbot')], default='WEB', max_length=20),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('RESCHEDULED', 'Rescheduled'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('MISSED', 'Missed')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='appointment',
            name='clinic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='appointments.clinic'),
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('specialty', models.CharField(blank=True, max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('clinic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctors', to='appointments.clinic')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='appointments.doctor'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['preferred_date', 'preferred_time'], name='appointment_preferr_d357c4_idx'),
        ),
    ]
