# Generated by Django 5.2.14 on 2026-05-29 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('care_team_name', models.CharField(default='Afya Mkononi Care Team', help_text='Display name for the human support team.', max_length=120)),
                ('whatsapp_number', models.CharField(blank=True, help_text='International format, digits only, no "+" or spaces — e.g. 254712345678. Leave blank to hide the WhatsApp button.', max_length=20)),
                ('whatsapp_prefill_message', models.CharField(blank=True, default="Hello Afya Mkononi, I'd like to talk to a member of the care team.", help_text='Message pre-filled in WhatsApp when a patient taps the button.', max_length=300)),
                ('support_hours', models.CharField(blank=True, default='Mon-Fri, 8am-6pm EAT', help_text='Shown under the human support card.', max_length=120)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site settings',
                'verbose_name_plural': 'Site settings',
            },
        ),
    ]
