# Generated by Django 5.2.14 on 2026-07-11 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar_choice',
            field=models.CharField(blank=True, help_text='Key of a chosen built-in avatar. Ignored when a photo is uploaded.', max_length=32),
        ),
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other'), ('PREFER_NOT', 'Prefer not to say')], max_length=12),
        ),
    ]
