# Generated by Django 5.2.14 on 2026-05-29 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HealthTip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(help_text='The body of the tip. A sentence or two works best.')),
                ('image', models.ImageField(blank=True, help_text='Optional. A soft placeholder is shown when no image is set.', upload_to='health_tips/')),
                ('category', models.CharField(choices=[('GENERAL', 'General Wellness'), ('NUTRITION', 'Nutrition'), ('MENTAL_HEALTH', 'Mental Health'), ('PREVENTION', 'Prevention'), ('MATERNAL', 'Maternal & Child'), ('CHRONIC', 'Chronic Conditions')], default='GENERAL', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Only active tips appear in the daily rotation.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_active', 'created_at'], name='health_tips_is_acti_e1094f_idx')],
            },
        ),
    ]
