# Generated by Django 5.2.14 on 2026-06-09 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_tips', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='healthtip',
            old_name='description',
            new_name='content',
        ),
        migrations.AddField(
            model_name='healthtip',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='healthtip',
            name='image',
            field=models.ImageField(blank=True, help_text='Optional. A soft placeholder is shown when no image is set.', null=True, upload_to='health_tips/'),
        ),
    ]
