# Generated by Django 5.2.14 on 2026-06-18 16:26

import apps.chatbot.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_rename_to_conversation_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='attachment',
            field=models.FileField(blank=True, help_text='Optional file shared with this message (image, PDF, DOCX, or TXT).', null=True, upload_to='chat_attachments/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp', 'pdf', 'docx', 'txt']), apps.chatbot.models.validate_attachment_size]),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_content',
            field=models.TextField(blank=True),
        ),
    ]
